config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :kittens

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |f|
      f.html
      f.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find params[:id]

    respond_to do |f|
      f.html
      f.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: "Congrats on adding new kitten!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find params[:id]
  end


  def update
    @kitten = Kitten.find params[:id]

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "Kitten is updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find params[:id]
    @kitten.destroy
    redirect_to :root, notice: "Oh, no.. What did you do!?"
  end

  private

  def kitten_params
    params.expect kitten: [:name, :age, :cuteness, :softness]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>

  <div>
    <%= f.label :cuteness %><br>
    <%= f.number_field :cuteness %>
  </div>

  <div>
    <%= f.label :softness %><br>
    <%= f.number_field :softness %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<hr>
<div class="kitten">
  <p>Name: <%= kitten.name %></p>
  <p>Age: <%= kitten.age %></p>
  <p>Cuteness: <%= kitten.cuteness %></p>
  <p>Softness: <%= kitten.softness %></p>
  <div class="buttons">
    <%= button_to "Delete", kitten_path(id: kitten.id), method: :delete %>
    <%= button_to "Edit", edit_kitten_path(id: kitten.id), method: :get %>
  </div>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<%= button_to "New Kitten", new_kitten_path, method: :get %>

<%= render(partial: "kitten", collection: @kittens, as: :kitten) %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>Kitten #<%=@kitten.id%></h1>
<%= render(partial: "kitten", locals: { kitten: @kitten } ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Odin Kittens">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <p class="<%= name %>"><%= message %></p>
    <% end %>

    <%= yield %>
  </body>
</html>